# Quick note on matrix dimensions in Python
* Vectors and matrices in python are a little weird
* A vector is NOT the same as a 1 column or 1 row matrix
* This can get tricky/confusing
* SciKit learn requires **matrices** as predictor (X) variables
* Other languages:
    * Same issues in Julia
    * Not matlab
    * Generally not in R either
 
* Only python has this part(vector this part)!

In [2]:
import numpy as np
xvec = np.zeros(10) # establish a matrix full of 0
xmat = np.zeros(shape=(10,1))
#xmat = np.zeros(shape=(1,10))
print(xvec.shape)
print(xmat.shape)
print(xvec)
print(xmat)

(10,)
(10, 1)
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


### Converting vectors to matrices

In [3]:
# Generate vector of zeros
xvec = np.zeros(10)
# Twp eqivalent methods to reshape as 10x1 matrices
print(xvec)
print('------------------------------------------------')

xmat1 = xvec[:,np.newaxis] # np.newaxi: actually a kind of pseudo index to create a dimension
print(xmat1.shape)
print(xmat1)
print('------------------------------------------------')

xmat2 = np.reshape(xvec,(10,1)) # Here reshape means that transform the first format to the second format
print(xmat2.shape)
print(xmat2)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
------------------------------------------------
(10, 1)
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
------------------------------------------------
(10, 1)
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
